/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hr.gregl.view;

import hr.gregl.controller.AdminController;
import hr.gregl.utilities.FileUtils;
import hr.gregl.utilities.MessageUtils;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.text.html.HTML.Attribute.DIR;

/**
 *
 * @author albert
 */
public class AdminPanel extends javax.swing.JPanel {

    private AdminController adminController;

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
        this.adminController = new AdminController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDeleteData = new javax.swing.JButton();
        btnLoadRssData1 = new javax.swing.JButton();

        setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1024, 680));
        setMinimumSize(new java.awt.Dimension(1024, 680));

        btnDeleteData.setBackground(new java.awt.Color(204, 0, 0));
        btnDeleteData.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        btnDeleteData.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteData.setText("Delete Data");
        btnDeleteData.setMargin(new java.awt.Insets(10, 14, 1, 14));
        btnDeleteData.setName(""); // NOI18N
        btnDeleteData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDataActionPerformed(evt);
            }
        });

        btnLoadRssData1.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        btnLoadRssData1.setText("Load RSS Data");
        btnLoadRssData1.setMargin(new java.awt.Insets(10, 14, 1, 14));
        btnLoadRssData1.setName(""); // NOI18N
        btnLoadRssData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadRssData1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(409, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLoadRssData1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(btnDeleteData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(btnLoadRssData1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnDeleteData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDataActionPerformed

        if (MessageUtils.showConfirmDialog(
                "Delete Data from Database",
                "Do you really want to delete all Data from the database?")) {
            try {
                // Delete Data from database
                adminController.deleteAllDataFromDatabase();
                // Delete all images in the directory
                String directoryPath = DIR + File.separator;
                FileUtils.deleteFilesInDirectory(Paths.get(directoryPath));
            } catch (Exception ex) {
                Logger.getLogger(ActorPanel.class.getName()).log(Level.SEVERE, null, ex);
                MessageUtils.showErrorMessage("Error", "Unable to delete data!");
            }
        }

    }//GEN-LAST:event_btnDeleteDataActionPerformed

    private void btnLoadRssData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadRssData1ActionPerformed
        adminController.parseAndSaveDataFromRSS();
    }//GEN-LAST:event_btnLoadRssData1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteData;
    private javax.swing.JButton btnLoadRssData1;
    // End of variables declaration//GEN-END:variables
}
